name: Deploy Laravel Application

on:
  push:
    branches:
      - dev # Atau branch lain yang Anda tentukan
  pull_request:
    branches:
      - dev # Akan berjalan ketika ada PR ke branch `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Deploy to Niagahoster
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -p 65002 -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@153.92.9.232 "
          cd /home/${{ secrets.SSH_USERNAME }}/public_html &&
          git fetch origin &&
          git reset --hard origin/main &&
          git pull origin main &&
          composer2 update --no-interaction --prefer-dist --optimize-autoloader &&
          php artisan config:cache"
